# Placeholder proguard rules file required by the Android Gradle Plugin
# Add keep rules below if R8 reports missing classes or removal of required APIs.

# Keep generated Flutter plugin registrant just in case
-keep class io.flutter.plugins.** { *; }

# Suppress warnings for javax.annotation types referenced by dependencies (generated by AGP)
-dontwarn javax.annotation.Nullable
-dontwarn javax.annotation.concurrent.GuardedBy
